//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExpense
    {
        public int Id { get; set; }
        public int JobID { get; set; }
        public Nullable<int> ExpenseID { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual ScheduleJob ScheduleJob { get; set; }
    }
}
