//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleJob()
        {
            this.JobExpenses = new HashSet<JobExpense>();
        }
    
        public int Id { get; set; }
        public int ServiceTypeID { get; set; }
        public int ClientID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EstimatedDuration { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public bool Complete { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobExpense> JobExpenses { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
